baseURL = 'https://mitchcambareri.com/'
languageCode = 'en-us'
title = 'Mitch Cambareri'
theme = 'PaperMod'
publishDir = "docs"

[params.profileMode]
    enabled = true
    title = "Mitch's Notebook"
    subtitle = "Infrastructure management, home lab configs, and notes."
    imageUrl = "na"
    imageWidth = 120
    imageHeight = 120

[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/mitchcambareri/"
[[params.socialIcons]]
    name = "github"
    url = "https://github.com/mitch84208"
[[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/mitchrox4eva"
[[params.socialIcons]]
    name = "facebook"
    url = "https://www.facebook.com/mitch.cambareri"